### ISSUE TITLE
Email fields not recognized as inputs

### ISSUE THREAD

**Issue by bintoro** [sblask/webextension-simple-form-fill#12]
For some reason, the extension won't fill `input` elements whose `type` is `email` – the context menu is empty. Any idea why this might be?

**Comment by eallsop** [comment]
I have exactly the same problem, but not for all email fields.
It didn't work when trying to set up a new Amazon account. When right clicking in the email field the list that came up only contained the word "Preferences" and none of the items I had entered.
This also happens on other sites I have tried.
But when I registered for GitHub to be able to enter this comment the email field worked perfectly.
I have always used "Autofill Forms" but only for manual entry of fields and that works on all the email fields I have mentioned. The only problem is that version of Autofill Forms is not Firefox 57 compatible and the new version is nowhere near as good.
Simple Form Fill (if the email field worked) would be even better than Autofill Forms as it is easy to enter the data in the list in any order you like.
The email field is the most important of the lot, firstly because it is probably used more than any other and secondly because manually entering the email risks making errors. 
I hope this can be fixed soon.

**Comment by bintoro** [comment]
> But when I registered for GitHub to be able to enter this comment the email field worked perfectly.

That's because that particular input field is of the type `text` even though it's expecting an email address. As long as `type="email"` is specified in the field's attributes, the issue seems to occur every time.

Actually I think I've solved this right now. It's a Firefox bug. I was looking through the extension code and started wondering if maybe Firefox doesn't recognize `email` fields as `editable`. And then I found this: https://bugzilla.mozilla.org/show_bug.cgi?id=1345081.

A workaround might be to display the items all the time and just not do anything if an item is selected outside of a form field.

**Comment by eallsop** [comment]
Thanks very much for your prompt response.

 

I admit I don’t understand all that was included in the link you sent.

 

What I don’t understand is why the current (non-webpage based extension) version of Autofill Forms works perfectly on these fields. Or is it some limitation of using webpage extensions that stops this, as the later webpage extension version of Autofill Forms does not work properly on email fields. (I can’t get it to work properly at all but on email fields the Autofill option does not even appear on the context menu when you right click on the field).

 

Being able to right click and enter an email is one of the most important things as far as I am concerned.

 

All I want to do is be able to right click whenever any text entry is required and select from a list – whether it is email, name, address etc.

 

I appreciate it is not your fault but if it can’t be made to work then I may be forced to look for a different browser where it will work when 57 comes in.

 

Keep up the good work. Apart from this issue I think your approach is fantastic. Exactly what I want.

 

Regards.

 

E. Allsop

**Comment by sblask** [comment]
So I guess this can be closed? SDK extensions and webextensions are completely different, which is why some things might work differently. In case you do change browsers, I have this extension published in the Chrome webstore too.

**Comment by bintoro** [comment]
@sblask What do you think about getting rid of the `editable` condition, i.e., simply showing the list of items no matter where the context menu was invoked?

**Comment by eallsop** [comment]
I think that sounds a good idea. 
At the moment it is difficult to use as it is not only the email field that doesn't work but others such as telephone number depending upon the website. 
I'd like to try your idea. 
Regards 
E. Allsop

**Comment by sblask** [comment]
Given that this is a bug in Firefox that will hopefully be fixed at some point and that doesn't exist in Chrome, I won't do any hacks. You should try the autocomplete if you need to fill email fields, I use only that...
