### ISSUE TITLE
Problem with duplicate entries

### ISSUE THREAD

**Issue by drkenrich** [sblask/webextension-simple-form-fill#25]
### New Issue Checklist (tick off like this: `[x]`)

- [ x] I checked existing issues (open and closed) for possible duplicates
- [x ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [ x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)
This is fairly simple and not a great problem, just ultimately less than optimum.

I use this with a long list of preference lines. As I built and edited the preferences over time I sometimes duplicated information from one line to another later in the list for better use. For example, I have several different business accounts. I've listed erch one separately with individual lines for "Business" "Account Number", Login Name", etc. What I found was that once I have a line with my username, duplicates of it will display in the Preferences editing list, but when I go to actual entry into a form file, only the first instance of the username several lines above will be displayed for choice. It's more optimum for me to have all the data for each business grouped together even though it causes duplication.

Depot- IHL
442xxx52
Kenneth C Rich
Public Express
37xxx000
Kenneth Rich
Fido Foods
417xxx81
Kenneth C Rich
Mom's Pies
441xxx43
Kenneth C Rich
BP for Hire
636xxx07
Kenneth C Rich
Library card
250xxx89
Kenneth Rich

Is there something I can tweak to turn on display of duplicates?

**Comment by sblask** [comment]
The autocomplete and context menu are line based, nothing much to do about it. For your use case, I recommend using comments, so you configure for example ` // ` as comment string and then build your entries like so:

```
442xxx52 // Depot- IHL
37xxx000 // Public Express
417xxx81 // Fido Foods
...
```
when you'd choose the first item, only `442xxx52` would be filled in. This is how I do this myself and it works well - especially with autocomplete because you can enter `dep`, get all matches including the first in your list and again only `442xxx52` would be filled in when you choose it. It also makes the list a lot shorter.
